name: math-583
channels:
  - conda-forge
dependencies:
  - python~=3.11

  # Core
  - scipy
  - scikit-image

  # Network
  #- conda-forge::python-igraph
  #- conda-forge::graph-tool
  
  #- conda-forge::networkx>=3.0.0
  
  # Plotting and visualization tools
  - matplotlib

  # Peformance/optimization
  #- numexpr

  # Documentation
  ##- sphinx
  
  #- toml
  ##- ipywidgets
  ##- conda-forge::myst-nb
  ##- conda-forge::myst-parser
  ##- conda-forge::sphinx-panels
  ##- conda-forge::sphinx-book-theme>=0.3.2
  ## - conda-forge::sphinx-autobuild
  ##- conda-forge::sphinx-comments # Hypothes.is comments and annotations    
  
  # Pip-only dependencies
  - pip
  - pip:
    - sphinx-autobuild
    - sphinx-design
    - sphinx-togglebutton
    - sphinx-comments # Hypothes.is comments and annotations    

    # https://github.com/executablebooks/sphinx-jupyterbook-latex/issues/97
    - sphinx-jupyterbook-latex[myst-nb]
    - sphinxcontrib-bibtex>=2.4.0
    - sphinx-book-theme>=0.3.2

    - sphinxcontrib-zopeext
    
    - myst-nb

    - tqdm

    - mmf-setup
    
    ##- ruamel-yaml
    ##- PyMaxflow>=1.3.0
    ##- uncertainties
    ##- scikit-learn
    #- statsmodels
    #- nasdaq_stock
    #- yfinance
    #- seaborn
    #- patsy
    #- deepdiff

env_specs:
  rtd:
    description: Limited environment needed to build the documentation.  No tools.
    packages:
      
  math-583:
    description: Environment spec for work and documentation.
    packages:
      - anaconda-project>=0.10.1
      
      - conda-forge::jupyter_nbextensions_configurator
      - pandoc
      - notebook
      - jupyter_console
      - qtconsole
      - sympy
      
      # Performance/profiling
      - line_profiler

      # To match CoCalc Anaconda2021
      - scipy==1.7.1
      - networkx==2.6.3
      
      # Testing
      - pytest-cov
      - pytest-flake8
      - pytest-html
      - pytest-xdist

      # Tools
      - jupytext
      - black
      - yapf
      - conda-forge::jupyter-black
      - sphobjinv  # Helps looking up intersphinx references

# Silence warnings about about notebooks without run commands
# See https://github.com/Anaconda-Platform/anaconda-project/issues/263#issuecomment-870004641
skip_imports:
  notebooks: true
